dist: trusty
sudo: required
language: bash
before_install:
 - curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
bash
notifications:
  slack: devops-team-otus:BiiLLy9uvoFYDmkma674MI33
