dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-08/run.sh |
  bash
notifications:
  slack:
    secure: S/hxdOtZVZTprsU7YWdndBvx+rfWLF0Kejp3Ae/UnPx4d4FdP9eEK9ZQmWZhkwmdpDWiKVDameDA+P4Ok+QL2zg6UNgK7a5/K2x2UTNvoirrWlJSDsVm+B71Do39Z7DuuNy1T2MTa+4Xb6KlzvKmb5WznXU7hFFKllO5o2XnpYaWNeS631o4GwvTiSsSjlndb3hn9twq4NQFzVBdCPqeWek90aeTC06b/AXltVk08GK/HRCVkvH1vMRHI+uDM0y+vre/6Z3E0AG1lhL5c3KCXw9oLecD/uXGXNggq6+qU0KP2UZ91xfrc3r2RDPwP68rqq2CULjcOUUMcnmmUGYtGcAtD8QW+9r6JmjoRvErMoEcg3/HGDCeH1WgSfq1Q/XnKDlXtDoRznHUWPrcGq7NnP3m2uEvS3F+6YdD+ivbfPEW36wPPKHgneNbbmaX+z+cmTI2S4jopBDGQge66mva4vwP7RwXyLoVvjvdlyag40gigz9oax7hL2XF4MbR5wD+rWrLSgIbbo4bb1VU/Vbi9UYTRhbvgScoseOAZFIlJQhQLss2/eddYifF8axdsjOdnx+O5Se1OSfNm/xOvXfp6OcFQ34YEIh4S6XnCvTWfipvL10tiTMFQKtgKKDz+1Lwd2C4L8MojjSoMOHZIkmte5eqcoa/xkpnU7YXMjbnE30=
