version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME_DOCKERHUB}/ui:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_PUB_PORT}:9292/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

    networks:
      - front_net
    depends_on:
      - post
      - comment
  post:
    image: ${USERNAME_DOCKERHUB}/post:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USERNAME_DOCKERHUB}/comment:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    depends_on:
      - post_db

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: ${BACK_SUBNET}
  front_net:
    ipam:
      config:
        - subnet: ${FRONT_SUBNET}
