kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 6YR02bCb4Yk+wtoyeHxN702K4gfULx/Akd0qYWLOYgs=
      - identity: {}
